name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:

  linux:
    runs-on: ubuntu-20.04
    name: build for Ubuntu
    steps:

    - uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@master
      with:
        name: crispy-guacamole
        path: /home/runner/work/crispy-guacamole/crispy-guacamole/target/debug/crispy-guacamole

  win:
    runs-on: windows-latest
    name: build for windows
    steps:
    - uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - uses: actions/upload-artifact@master
      with:
        name: crispy-guacamole
        path: /home/runner/work/crispy-guacamole/crispy-guacamole/target/debug/crispy-guacamole.exe 

  macos-build:
    runs-on: macos-11.0
    name: build for macOS
    steps:
    - uses: actions/checkout@v2
    - name: Install stable toolchain
    uses: actions-rs/toolchain@v1
    with:
    profile: minimal
    toolchain: stable
    override: true
    - name: Build
    run: cargo build --verbose